# Generated by Django 3.2 on 2021-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pictures"),
        ),
    ]
