# Generated by Django 3.2 on 2021-04-14 15:42

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=100,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=200,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
