# Generated by Django 3.2 on 2021-04-15 10:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20210414_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
