# Generated by Django 3.2 on 2021-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_alter_post_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="URL"),
        ),
    ]
