# Generated by Django 3.2 on 2021-04-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210420_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
