# Generated by Django 3.2 on 2021-04-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_comment_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='for_news',
            new_name='for_post',
        ),
    ]
